import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Facebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className="bg-slate-100 text-black">
        {children}
      </body>
    </html>
  );
}
